FROM python:3.8-slim

WORKDIR /app

# Install required system packages
RUN apt-get update && apt-get install -y \
    gcc \
    pkg-config \
    default-libmysqlclient-dev \
    && rm -rf /var/lib/apt/lists/*

COPY . .

RUN pip install flask mysqlclient

EXPOSE 5002

CMD ["python", "app.py"]







#stage 1: build stage
FROM python:3.8-slim AS build 


WORKDIR /app

# Install required system packages
RUN apt-get update && apt-get install -y \
gcc \
pkg-config \
default-libmysqlclient-dev 

COPY . .

RUN pip install flask mysqlclient

#stage2: [production stage]

FROM python:3.8-slim

WORKDIR /app

COPY --from=Build /app /app/

EXPOSE 5002

CMD ["python", "app.py"]